const moviesData = {
    "rental1": {
        title: "SpyXfamily",
        rating: 4.7,
        duration: "1h 55min",
        year: 2023,
        synopsis: "Một gia đình gián điệp bí mật nhưng lại đầy hài hước và ấm áp.",
        director: "Kazuhiro Furuhashi",
        cast: ["Takuya Eguchi", "Atsumi Tanezaki", "Saori Hayami"],
        genre: ["Action", "Comedy", "Family"],
        production: "Wit Studio & CloverWorks",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_1_SpyXFamily.png",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_SpyXFamily.png"
    },
    "rental2":{
        title: "Natra",
        rating: 4.5,
        duration: "1h 45min",
        year: 2021,
        synopsis: "Cuộc hành trình của cậu bé Natra đầy kịch tính và cảm động.",
        director: "Jianping Li",
        cast: ["Wei Zhao", "Bo Huang", "Jing Tian"],
        genre: ["Fantasy", "Adventure", "Animation"],
        production: "Beijing Enlight Media",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_2_Natra.png",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_Natra.png"
    },
    "rental3":{
        title: "Toypet",
        rating: 4.3,
        duration: "1h 30min",
        year: 2022,
        synopsis: "Một thế giới nơi đồ chơi có linh hồn và cùng nhau trải qua nhiều cuộc phiêu lưu.",
        director: "Tomoya Takahashi",
        cast: ["Hana Kanazawa", "Yuki Kaji", "Rie Kugimiya"],
        genre: ["Adventure", "Fantasy", "Animation"],
        production: "Toei Animation",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_3_ToyPet.png",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_ToyPet.png"
    },
    "rental4":{
        title: "Chuột nhí và sứ mệnh Argonuts",
        rating: 4.6,
        duration: "1h 40min",
        year: 2023,
        synopsis: "Một chú chuột nhỏ với ước mơ lớn, tham gia cuộc phiêu lưu trên biển.",
        director: "David Alaux",
        cast: ["Paul Borne", "Emmanuel Curtil", "Kaycie Chase"],
        genre: ["Family", "Adventure", "Animation"],
        production: "TAT Productions",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_4_ChuotNhi.png",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_ChuotNhi.webp"
    },
    "rental5":{
        title: "Thỏ gà rà kho báu",
        rating: 4.4,
        duration: "1h 50min",
        year: 2022,
        synopsis: "Hành trình truy tìm kho báu đầy thú vị của những người bạn động vật.",
        director: "Ben Stassen",
        cast: ["Danny Fehsenfeld", "Mark Irons", "Laila Berzins"],
        genre: ["Adventure", "Comedy", "Animation"],
        production: "nWave Pictures",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_5_ThoGa.png",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_ThoGa.png"
    },
        "rental6":{
            title: "Mèo Ma Bê Tha",
            rating: 4.5,
            duration: "1h 45min",
            year: 2023,
            synopsis: "Một chú mèo tinh nghịch vô tình lạc vào thế giới phép thuật và phải tìm cách trở về nhà.",
            director: "Nguyễn Minh Quân",
            cast: ["Lê Hoàng", "Bảo Anh", "Trung Dũng"],
            genre: ["Hoạt Hình", "Phiêu Lưu"],
            production: "Cat Studio",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_6_MeoMa.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_MeoMa.png"
        },
        "rental7":{
            title: "Mòng Biển Manou",
            rating: 4.3,
            duration: "1h 30min",
            year: 2022,
            synopsis: "Manou là một chú chim nhỏ sống trong một đàn mòng biển và cố gắng chứng minh khả năng của mình.",
            director: "Christian Haas",
            cast: ["Kate Winslet", "Willem Dafoe"],
            genre: ["Hoạt Hình", "Gia Đình"],
            production: "LUXX Studios",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_7_MongBien.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_MongBien.png"
        },
        "rental8":{
            title: "Mèo Béo Siêu Đẳng",
            rating: 4.6,
            duration: "1h 40min",
            year: 2023,
            synopsis: "Một chú mèo béo với siêu năng lực giúp đỡ những người bạn trong khu phố khỏi nguy hiểm.",
            director: "John Lasseter",
            cast: ["Tom Holland", "Emma Watson"],
            genre: ["Hoạt Hình", "Hài Hước"],
            production: "DreamWorks Animation",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_8_MeoBeo.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_MeoBeo.png"
        },
        "rental9":{
            title: "Cậu Bé Cá Heo",
            rating: 4.7,
            duration: "1h 35min",
            year: 2022,
            synopsis: "Một cậu bé với khả năng đặc biệt có thể giao tiếp với cá heo và bảo vệ đại dương.",
            director: "David Hand",
            cast: ["Noah Jupe", "Scarlett Johansson"],
            genre: ["Hoạt Hình", "Phiêu Lưu"],
            production: "Blue Ocean Studios",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_9_CBCaHeo.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_CBCaHeo.png"
        },
        "rental10":{
            title: "Shin - Nhật Ký Khủng Long",
            rating: 4.5,
            duration: "1h 38min",
            year: 2023,
            synopsis: "Shin tìm thấy một quả trứng khủng long và quyết định nuôi nó, nhưng rồi gặp phải rắc rối lớn.",
            director: "Takashi Yamazaki",
            cast: ["Shinnosuke Nohara", "Keiko Toda"],
            genre: ["Hoạt Hình", "Hài Hước"],
            production: "Toho Animation",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_10_Shin.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_Shin.png"
        },
        "rental11":{
            title: "Dino King",
            rating: 4.8,
            duration: "1h 50min",
            year: 2021,
            synopsis: "Hành trình phiêu lưu của một chú khủng long con tìm kiếm gia đình mình trong thế giới cổ đại.",
            director: "Kim Young-heon",
            cast: ["Lee Hyung-seok", "Kim Eun-hee"],
            genre: ["Hoạt Hình", "Phiêu Lưu"],
            production: "Next Entertainment World",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_11_DinoKing.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_DinoKing.png"
        },
        "rental12":{
            title: "Conan - Kho Báu Dưới Đáy Đại Dương",
            rating: 4.9,
            duration: "1h 45min",
            year: 2024,
            synopsis: "Conan và nhóm bạn khám phá bí ẩn của một kho báu bị chôn vùi dưới đáy đại dương.",
            director: "Gosho Aoyama",
            cast: ["Minami Takayama", "Kappei Yamaguchi"],
            genre: ["Hoạt Hình", "Trinh Thám"],
            production: "TMS Entertainment",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_12_Conan.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_Conan.png"
        },
        "rental13":{
            title: "Pororo - Cuộc Phiêu Lưu Đến Dinh Thự Rồng",
            rating: 4.2,
            duration: "1h 30min",
            year: 2023,
            synopsis: "Pororo và những người bạn tìm đường đến một dinh thự rồng đầy bí ẩn.",
            director: "Kim Jin-ho",
            cast: ["Pororo", "Crong", "Eddy"],
            genre: ["Hoạt Hình", "Gia Đình"],
            production: "Iconix Entertainment",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_13_Pororo.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_Pororo.png"
        },
        "rental14":{
            title: "Bố Gà Siêu Đẳng",
            rating: 4.5,
            duration: "1h 33min",
            year: 2022,
            synopsis: "Một chú gà trống quyết tâm bảo vệ đàn con của mình khỏi những mối nguy hiểm.",
            director: "Carlos Saldanha",
            cast: ["Chris Pratt", "Zendaya"],
            genre: ["Hoạt Hình", "Hài Hước"],
            production: "Blue Sky Studios",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_14_BoGa.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_BoGa.png"
        },
        "rental15":{
            title: "Mèo Siêu Quậy Ở Viện Bảo Tàng",
            rating: 4.4,
            duration: "1h 28min",
            year: 2023,
            synopsis: "Một chú mèo thông minh phá giải những bí ẩn tại viện bảo tàng vào ban đêm.",
            director: "Pierre Perifel",
            cast: ["Jack Black", "Jennifer Aniston"],
            genre: ["Hoạt Hình", "Phiêu Lưu"],
            production: "Universal Pictures",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_15_MeoSieuQuay.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_MeoSieuQuay.png"
        },
        "rental16":{
            title: "Space Dogs",
            rating: 4.3,
            duration: "1h 25min",
            year: 2020,
            synopsis: "Hành trình của hai chú chó dũng cảm trong sứ mệnh du hành vũ trụ.",
            director: "Inna Evlannikova",
            cast: ["Alicia Silverstone", "Sam Witwer"],
            genre: ["Hoạt Hình", "Khoa Học Viễn Tưởng"],
            production: "KinoAtis",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_16_SpaceDog.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_SpaceDog.png"
        },
        "rental17":{
            title: "Mavka: Người Gác Rừng",
            rating: 4.7,
            duration: "1h 39min",
            year: 2023,
            synopsis: "Mavka, một linh hồn rừng xanh, phải lựa chọn giữa tình yêu và nhiệm vụ bảo vệ thiên nhiên.",
            director: "Oleh Malamuzh, Oleksandra Ruban",
            cast: ["Nataliya Denisenko", "Artem Pivovarov"],
            genre: ["Hoạt Hình", "Phiêu Lưu"],
            production: "Animagrad Animation Studio",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_18_Mavaka.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_Mavaka.png"
        },
        "rental18":{
            title: "Katak: Chú Cá Tầm Dũng Cảm",
            rating: 4.6,
            duration: "1h 25min",
            year: 2023,
            synopsis: "Katak, một chú cá tầm nhỏ bé, quyết định thực hiện một hành trình vĩ đại để tìm lại nguồn cội của mình.",
            director: "Christine Dallaire-Dupont, Nicola Lemay",
            cast: ["Xavier Dolan", "Rick Jones"],
            genre: ["Hoạt Hình", "Phiêu Lưu"],
            production: "10th Ave Productions",
            background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_17_Katak.png",
            background: "/Web-Movie-main/image/PhimLe_ThieuNhi/ThieuNhi/background_Katak.png"
        }
    };

