const moviesData = {
    "rental19": {
        title: "The Hunger Games",
        rating: 4.7,
        duration: "2h 22min",
        year: 2012,
        synopsis: "Katniss Everdeen tình nguyện tham gia một cuộc chiến sinh tử được tổ chức hàng năm để bảo vệ em gái mình.",
        director: "Gary Ross",
        cast: ["Jennifer Lawrence", "Josh Hutcherson"],
        genre: ["Hành Động", "Phiêu Lưu"],
        production: "Lionsgate",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_1_theHunger.webp",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_theHunger.webp"
    },
    "rental20": {
        title: "Blade Runner 2049",
        rating: 4.8,
        duration: "2h 44min",
        year: 2017,
        synopsis: "Một người Blade Runner trẻ tuổi phát hiện ra một bí mật có thể thay đổi toàn bộ xã hội.",
        director: "Denis Villeneuve",
        cast: ["Ryan Gosling", "Harrison Ford"],
        genre: ["Khoa Học Viễn Tưởng", "Hành Động"],
        production: "Warner Bros.",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_2_BladeRunner.webp",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_BladeRunner.webp"
    },
    "rental21": {
        title: "Zone 414",
        rating: 4.5,
        duration: "1h 38min",
        year: 2021,
        synopsis: "Một thám tử tư được thuê để tìm một cô gái mất tích trong thành phố của người máy.",
        director: "Andrew Baird",
        cast: ["Guy Pearce", "Matilda Lutz"],
        genre: ["Hành Động", "Bí Ẩn"],
        production: "Saban Films",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_Zone.webp",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_3_Zone.webp"
    },
    "rental22": {
        title: "Hana Bí Ẩn",
        rating: 4.6,
        duration: "1h 45min",
        year: 2019,
        synopsis: "Một cô gái trẻ khám phá ra sự thật về quá khứ của mình khi điều tra một vụ án bí ẩn.",
        director: "Hideo Nakata",
        cast: ["Haruka Ayase", "Takeru Satoh"],
        genre: ["Kinh Dị", "Huyền Bí"],
        production: "Toho Company",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_4_Hanna.webp",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_Hanna.webp"
    },
    "rental23": {
        title: "Điệp Viên XXX",
        rating: 4.7,
        duration: "2h 4min",
        year: 2002,
        synopsis: "Một tay đua xe đường phố được tuyển dụng để thực hiện một nhiệm vụ nguy hiểm.",
        director: "Rob Cohen",
        cast: ["Vin Diesel", "Asia Argento"],
        genre: ["Hành Động", "Phiêu Lưu"],
        production: "Revolution Studios",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_5_DiepVien.webp",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_DiepVien.webp"
    },
    "rental24": {
        title: "Hỏa Ngục Inferno",
        rating: 4.6,
        duration: "2h 1min",
        year: 2016,
        synopsis: "Robert Langdon tỉnh dậy trong một bệnh viện ở Ý mà không nhớ gì, và phải giải mã một bí ẩn nguy hiểm.",
        director: "Ron Howard",
        cast: ["Tom Hanks", "Felicity Jones"],
        genre: ["Bí Ẩn", "Hành Động"],
        production: "Columbia Pictures",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_6_HoaNguc.webp",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_HoaNguc.webp"
    },
    "rental25": {
        title: "Bàn Tay Diệt Quỷ",
        rating: 4.5,
        duration: "1h 55min",
        year: 2022,
        synopsis: "Một người đàn ông có khả năng đặc biệt chống lại ma quỷ và các thế lực tà ác.",
        director: "Kim Joo-hwan",
        cast: ["Park Seo-joon", "Woo Do-hwan"],
        genre: ["Kinh Dị", "Hành Động"],
        production: "Lotte Entertainment",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_7_BanTayDQ.webp",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_BanTayDQ.webp"
    },
    "rental26": {
        title: "Pawn: Cục Nợ Hóa Cục Cưng",
        rating: 4.6,
        duration: "1h 53min",
        year: 2020,
        synopsis: "Một tay đòi nợ thuê bất đắc dĩ trở thành người bảo hộ cho một cô bé đáng yêu.",
        director: "Kang Dae-gyu",
        cast: ["Sung Dong-il", "Ha Ji-won"],
        genre: ["Tâm Lý", "Gia Đình"],
        production: "CJ Entertainment",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_8_Pawn.webp",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_Pawn.webp"
    },
    "rental27": {
        title: "Thiếu Gia Kỹ Phường",
        rating: 4.3,
        duration: "1h 50min",
        year: 2021,
        synopsis: "Một thiếu gia giàu có bị cuốn vào thế giới kỹ nữ và phải tìm cách vượt qua những thử thách để khẳng định bản thân.",
        director: "Trần Hữu Tài",
        cast: ["Ngô Kiến Huy", "Khả Như"],
        genre: ["Hài Hước", "Tình Cảm"],
        production: "CJ Entertainment",
        background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_9_TGKP.webp",
        background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_TGKP.webp"
    },
    "rental28": {
    title: "Thám Tử Hong Gil Dong",
    rating: 4.3,
    duration: "2h 5min",
    year: 2016,
    synopsis: "Hong Gil Dong - một thám tử tài ba với những vụ án bí ẩn chưa từng có tiền lệ.",
    director: "Jo Sung-hee",
    cast: ["Lee Je-hoon", "Go Ara"],
    genre: ["Hành Động", "Trinh Thám"],
    production: "CJ Entertainment",
    background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_10_TTHGD.webp",
    background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_TTHGD.webp"
},
"rental29": {
    title: "Along with the Gods: The Two Worlds",
    rating: 4.8,
    duration: "2h 19min",
    year: 2017,
    synopsis: "Một người lính qua đời và được ba vệ thần dẫn dắt qua bảy thử thách ở thế giới bên kia.",
    director: "Kim Yong-hwa",
    cast: ["Ha Jung-woo", "Cha Tae-hyun"],
    genre: ["Hành Động", "Giả Tưởng"],
    production: "Lotte Entertainment",
    background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_11_Along.webp",
    background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_Along.webp"
},
"rental30": {
    title: "Dog Dog Days: Sen Boss Sum Vầy",
    rating: 4.2,
    duration: "1h 45min",
    year: 2023,
    synopsis: "Những câu chuyện vui nhộn về tình bạn giữa con người và những chú chó trung thành.",
    director: "Trần Bảo Sơn",
    cast: ["Diễn viên C", "Diễn viên D"],
    genre: ["Hài Hước", "Gia Đình"],
    production: "Hãng Phim Pet Lover",
    background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_12_DogDay.webp",
    background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_DogDay.webp"
},
"rental31": {
    title: "Bóng Ma Phantom",
    rating: 4.6,
    duration: "2h 10min",
    year: 2023,
    synopsis: "Một điệp viên phải đối mặt với âm mưu và những thế lực ngầm trong cuộc chiến gián điệp căng thẳng.",
    director: "Lee Hae-young",
    cast: ["Sol Kyung-gu", "Lee Hanee"],
    genre: ["Hành Động", "Trinh Thám"],
    production: "CJ Entertainment",
    background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_13_BongMa.webp",
    background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_BongMa.webp"
},
"rental32": {
    title: "Master: Ông Trùm",
    rating: 4.7,
    duration: "2h 15min",
    year: 2016,
    synopsis: "Một cuộc rượt đuổi đầy kịch tính giữa cảnh sát và những tay trùm tội phạm.",
    director: "Cho Ui-seok",
    cast: ["Lee Byung-hun", "Kang Dong-won"],
    genre: ["Hành Động", "Tội Phạm"],
    production: "CJ Entertainment",
    background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_14_Master.webp",
    background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_Master.webp"
},
"rental33": {
    title: "White Snake: Bạch Xà Duyên Khởi",
    rating: 4.5,
    duration: "1h 39min",
    year: 2019,
    synopsis: "Câu chuyện về Bạch Xà và mối tình ngang trái đầy lãng mạn với một chàng trai phàm nhân.",
    director: "Amp Wong, Zhao Ji",
    cast: ["Zhang Zhe", "Yang Tianxiang"],
    genre: ["Hoạt Hình", "Giả Tưởng"],
    production: "Light Chaser Animation Studios",
    background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_15_WhiteSnake.webp",
    background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_WhiteSnake.webp"
},
"rental34": {
    title: "Bùa Hình Nhân Hoon Payon",
    rating: 4.2,
    duration: "1h 50min",
    year: 2023,
    synopsis: "Một câu chuyện kinh dị về những bùa chú đen tối và sự trỗi dậy của linh hồn oan khuất.",
    director: "Phontharis Chotkijsadarsopon",
    cast: ["Mario Maurer", "Yaya Urassaya"],
    genre: ["Kinh Dị", "Tâm Linh"],
    production: "GDH 559",
    background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_16_BuaHinhNhan.webp",
    background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_BuaHinhNhan.webp"
},
"rental35": {
    title: "I Did It My Way: Tiềm Hành",
    rating: 4.3,
    duration: "2h 3min",
    year: 2024,
    synopsis: "Một sĩ quan cảnh sát chìm phải đối mặt với những nguy hiểm trong thế giới ngầm.",
    director: "Herman Yau",
    cast: ["Andy Lau", "Eddie Peng"],
    genre: ["Hành Động", "Tội Phạm"],
    production: "Emperor Motion Pictures",
    background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_17_TiemHanh.webp",
    background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_TiemHanh.webp"
},
"rental36": {
    title: "Monster Hunter: Thợ Săn Quái Thú",
    rating: 4.0,
    duration: "1h 43min",
    year: 2020,
    synopsis: "Một đội quân tinh nhuệ bị cuốn vào thế giới của những con quái thú khổng lồ và phải chiến đấu để sinh tồn.",
    director: "Paul W.S. Anderson",
    cast: ["Milla Jovovich", "Tony Jaa"],
    genre: ["Hành Động", "Giả Tưởng"],
    production: "Screen Gems",
    background1: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_18_MonstrerHunter.webp",
    background: "/Web-Movie-main/image/PhimLe_ThieuNhi/PhimLe/background_MonstrerHunter.webp"
}
};
